timestamp:
  key: time
  visible: true

logger:
  key: logger
  visible: true
  padding: 0

caller:
  key: caller
  visible: false
  padding: 0

level:
  key: level
  visible: true
  padding: 5

message:
  key: msg
  padding: 0